AWSTemplateFormatVersion: "2010-09-09"
Resources:
  FrontendS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "nodejs-project-frontend-bucket"

  BackendEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.micro"
      ImageId: "ami-0c02fb55956c7d316" # Amazon Linux 2 AMI
      KeyName: "your-key-pair-name" # Replace with your EC2 Key Pair
      SecurityGroupIds:
        - !Ref BackendSecurityGroup
      Tags:
        - Key: "Name"
          Value: "BackendInstance"

  BackendSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Allow HTTP and SSH access"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: 3000
          ToPort: 3000
          CidrIp: "0.0.0.0/0"
